model:
    name: 'CNNRULPredictor'
    in_channels: 1
    channels: 16
    input_height: 100
    input_width: 1000
    epochs: 1000
    batch_size: 128
    evaluate_freq: 100
train_test_split:
    name: 'MIX100TrainTestSplitter'
    cell_data_path:
        - 'data/processed/CALCE'
        - 'data/processed/RWTH'
        - 'data/processed/UL_PUR'
        - 'data/processed/HNEI'
        - 'data/processed/MATR'
        - 'data/processed/HUST'
feature:
    name: 'VoltageCapacityMatrixFeatureExtractor'
    diff_base: 9
    max_cycle_index: 99
    use_precalculated_qdlin: True
label:
    name: 'RULLabelAnnotator'
label_transformation:
    name: 'SequentialDataTransformation'
    transformations:
        - name: 'LogScaleDataTransformation'
        - name: 'ZScoreDataTransformation'
