model:
    name: 'LinearRegressionRULPredictor'
train_test_split:
    name: 'CRUSHTrainTestSplitter'
    cell_data_path:
        - 'data/processed/CALCE'
        - 'data/processed/RWTH'
        - 'data/processed/UL_PUR'
        - 'data/processed/SNL'
        - 'data/processed/HNEI'
feature:
    name: 'VarianceModelFeatureExtractor'
    interp_dims: 1000
    critical_cycles:
        - 2
        - 9
        - 19
    use_precalculated_qdlin: True
label:
    name: 'RULLabelAnnotator'
    eol_soh: 0.9
feature_transformation:
    name: 'ZScoreDataTransformation'
label_transformation:
    name: 'SequentialDataTransformation'
    transformations:
        - name: 'LogScaleDataTransformation'
        - name: 'ZScoreDataTransformation'
